name: Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
          cd ${{github.workspace}}/example/external
          git clone https://github.com/astomih/sinen
          cd ..

    - name: Install libraries
      run: |
          cd ${{github.workspace}}/example/android-project/app/jni
          ln -s ${{github.workspace}}/example ./singa
          ln -s ${{github.workspace}}/example/external/sinen ./sinen
          git clone https://github.com/astomih/SDL.git
          git clone https://github.com/astomih/SDL_image.git
          git clone https://github.com/astomih/SDL_mixer.git
          git clone https://github.com/astomih/SDL_ttf.git
          git clone https://github.com/astomih/SDL_net.git
          mv SDL SDL2
          mv SDL_image SDL2_image
          mv SDL_mixer SDL2_mixer
          mv SDL_ttf SDL2_ttf
          mv SDL_net SDL2_net
          mv CMakeLists-SDL_net.txt SDL2_net
          cd SDL2_net
          mv CMakeLists-SDL_net.txt CMakeLists.txt
          cd ${{github.workspace}}/example
    - name: set up JDK 11

      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    

    - name: Grant execute permission for gradlew
      run: |
          pwd
          cd ${{github.workspace}}/example/android-project
          chmod +x gradlew
    - name: Build with Gradle
      run: |
          pwd
          cd ${{github.workspace}}/example/android-project
          ./gradlew build
