name: Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install libraries
      run: |
          cd ${{github.workspace}}/demo/android-project/app/jni
          ln -s ${{github.workspace}}/demo ./demo
          ln -s ${{github.workspace}} ./sinen
          ln -s ${{github.workspace}}/script ./script
          git submodule update --init --recursive
          mv ${{github.workspace}}/external/SDL2 .
          mv ${{github.workspace}}/external/SDL2_image .
          mv ${{github.workspace}}/external/SDL2_mixer .
          mv ${{github.workspace}}/external/SDL2_net .
          mv ${{github.workspace}}/external/SDL2_ttf .
          cd ${{github.workspace}}/demo
          mkdir -p ${{github.workspace}}/demo/android-project/app/src/main/assets && cp -r data ${{github.workspace}}/demo/android-project/app/src/main/assets
    - name: set up JDK 11

      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    

    - name: Grant execute permission for gradlew
      run: |
          pwd
          cd ${{github.workspace}}/demo/android-project
          chmod +x gradlew
    - name: Build with Gradle
      run: |
          pwd
          cd ${{github.workspace}}/demo/android-project
          ./gradlew build
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: android
        path: demo/android-project
  deploy:
    concurrency: ci-${{ github.ref }}
    needs: [build] # The second job must depend on the first one to complete before running and uses ubuntu-latest instead of windows.
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download Artifacts
      uses: actions/download-artifact@v1
      with:
        name: android
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages
        folder: 'android'
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        target-folder: android