name: Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
          cd ${{github.workspace}}/example/external
          git clone https://github.com/astomih/sinen
          cd ..

    - name: Install libraries
      run: |
          cd ${{github.workspace}}/example/android-project/app/jni
          ln -s ${{github.workspace}}/example ./singa
          ln -s ${{github.workspace}}/example/external/sinen ./sinen
          cd ${{github.workspace}}/example
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    

    - name: Grant execute permission for gradlew
      run: |
          pwd
          cd ${{github.workspace}}/example/android-project
          chmod +x gradlew
    - name: Build with Gradle
      run: |
          pwd
          cd ${{github.workspace}}/example/android-project
          ./gradlew build
