name: Documents

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Main documents action
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - run: |
          cp ./README.md ./docs/docs/index.md
          cd docs
          pip install mkdocs-material
          mkdocs gh-deploy --force
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@1.9.1
      with:
        doxyfile-path: 'tools/doxygen/Doxyfile'
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: documents
        path: docs/doxygen/html
  deploy:
    concurrency: ci-${{ github.ref }}
    needs: [build] # The second job must depend on the first one to complete before running and uses ubuntu-latest instead of windows.
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download Artifacts
      uses: actions/download-artifact@v1
      with:
        name: documents
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages
        folder: documents
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        target-folder: doxygen