name: Doxygen

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@1.9.1
      run: mkdir docs/html && touch docs/html/.nojekyll
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages
        folder: docs/html
        ssh-key: ${{ secrets.DEPLOY_KEY }}