name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      

    - name: Install libraries
      run: sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse" && sudo apt-get update -y -qq && sudo apt-get update -y -qq &&  sudo apt-get install ninja libglew-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev libopenal-dev

    - name: Setup Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.0.3
      

    - name: Configure CMake
      run: cmake -G Ninja -B ${{github.workspace}}/build

    - name: Build
      # Build your program with the given configuration
      run: cd build && ninja